package com.example.companio.utils

val labelMap = mapOf(
    "person" to "người",
    "bicycle" to "xe đạp",
    "car" to "xe hơi",
    "motorcycle" to "xe máy",
    "airplane" to "máy bay",
    "bus" to "xe buýt",
    "train" to "tàu hỏa",
    "truck" to "xe tải",
    "boat" to "thuyền",
    "traffic light" to "đèn giao thông",
    "fire hydrant" to "trụ cứu hỏa",
    "street sign" to "biển báo đường",
    "stop sign" to "biển dừng",
    "parking meter" to "đồng hồ đỗ xe",
    "bench" to "ghế dài",
    "bird" to "chim",
    "cat" to "mèo",
    "dog" to "chó",
    "horse" to "ngựa",
    "sheep" to "cừu",
    "cow" to "bò",
    "elephant" to "voi",
    "bear" to "gấu",
    "zebra" to "ngựa vằn",
    "giraffe" to "hươu cao cổ",
    "hat" to "mũ",
    "backpack" to "ba lô",
    "umbrella" to "ô",
    "shoe" to "giày",
    "eye glasses" to "kính mắt",
    "handbag" to "túi xách",
    "tie" to "cà vạt",
    "suitcase" to "vali",
    "frisbee" to "đĩa bay",
    "skis" to "ván trượt tuyết",
    "snowboard" to "ván trượt tuyết",
    "sports ball" to "bóng thể thao",
    "kite" to "diều",
    "baseball bat" to "gậy bóng chày",
    "baseball glove" to "găng bóng chày",
    "skateboard" to "ván trượt",
    "surfboard" to "ván lướt",
    "tennis racket" to "vợt tennis",
    "bottle" to "chai",
    "plate" to "đĩa",
    "wine glass" to "ly rượu",
    "cup" to "cốc",
    "fork" to "nĩa",
    "knife" to "dao",
    "spoon" to "muỗng",
    "bowl" to "bát",
    "banana" to "chuối",
    "apple" to "táo",
    "sandwich" to "bánh mì kẹp",
    "orange" to "cam",
    "broccoli" to "bông cải xanh",
    "carrot" to "cà rốt",
    "hot dog" to "xúc xích kẹp",
    "pizza" to "bánh pizza",
    "donut" to "bánh donut",
    "cake" to "bánh kem",
    "chair" to "ghế",
    "couch" to "ghế sofa",
    "potted plant" to "cây trồng trong chậu",
    "bed" to "giường",
    "mirror" to "gương",
    "dining table" to "bàn ăn",
    "window" to "cửa sổ",
    "desk" to "bàn làm việc",
    "toilet" to "bồn cầu",
    "door" to "cánh cửa",
    "tv" to "tivi",
    "laptop" to "máy tính xách tay",
    "mouse" to "chuột máy tính",
    "remote" to "điều khiển",
    "keyboard" to "bàn phím",
    "cell phone" to "điện thoại",
    "microwave" to "lò vi sóng",
    "oven" to "lò nướng",
    "toaster" to "máy nướng bánh mì",
    "sink" to "bồn rửa",
    "refrigerator" to "tủ lạnh",
    "blender" to "máy xay",
    "book" to "sách",
    "clock" to "đồng hồ",
    "vase" to "bình hoa",
    "scissors" to "kéo",
    "teddy bear" to "gấu bông",
    "hair drier" to "máy sấy tóc",
    "toothbrush" to "bàn chải đánh răng",
    "hair brush" to "lược"
)
